### ISSUE TITLE
Helm Support

### ISSUE THREAD

**Issue by Xaseron** [micronaut-projects/micronaut-kubernetes#133]
[Helm](https://github.com/helm/helm) is the de-facto standard for running and managing applications with Kubernetes. We rely heavily on it and we put our `application.yaml` inside a configMap.
For each feature branch we deployed our application into the same namespace. Therefore there a lot of configMaps with `application.yaml`s. 
e.g.:`13:50:45.410 [main] INFO  i.m.d.c.c.DistributedPropertySourceLocator - Resolved 21 configuration sources from client: compositeConfigurationClient(kubernetes)`
We need an easy mechanism to filter these configMaps.
Currently we have to change the `bootstrap.yaml` in each branch and don't forget to change it back before merging it. e.g.:
```yaml
kubernetes:
  client:
    config-maps:
      labels:
        - "app.kubernetes.io/instance" : myapplication-my-feature-branch
```

It would be awesome to have some native support for Helm.
That we can enable a flag that automatically gets the `app.kubernetes.io/instance` label from the application pod and uses it for filtering the config-maps and secrets.

**Comment by graemerocher** [comment]
seems like a good idea, would you consider submitting a PR?

**Comment by Xaseron** [comment]
Yes, i will do it.
I suggest a general approach that is not specific to Helm. e.g.
```yaml
kubernetes:
  client:
    config-maps:
       include-by-pod-labels:
          - "app.kubernetes.io/instance"
```

**Comment by graemerocher** [comment]
Seems reasonable to me

**Comment by alvarosanchez** [comment]
@Xaseron let's make it:

```yaml
kubernetes:
  client:
    config-maps:
       pod-labels:
          - "app.kubernetes.io/instance"
```

Let me know whether you have questions when implementing it.
