### ISSUE TITLE
Add a configuration option to enable/disable secret support

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-kubernetes#29]
It should be disabled by default, and would be possible to enable with:

```yaml
kubernetes:
  client:
    secrets:
      enabled: true
```
