### ISSUE TITLE
Manual service configuration not read from boostrap.yml

### ISSUE THREAD

**Issue by bjor-joh** [micronaut-projects/micronaut-kubernetes#305]
I'm trying to configure service discovery in kubernetes for a GRPC service. 
The service I'm trying to discover is a multi-port service and is therefore in need of manual service confguration. 
However, I cannot get micronaut to pick-up my service config. 

I have followed the guide available [here](https://micronaut-projects.github.io/micronaut-kubernetes/latest/guide/index.html#_service_discovery_modes)

This is what my `boostrap.yml` looks like

```
kubernetes:
  client:
    discovery:
      includes:
        - foo-service
      services:
        - foo-service:
            port: grpc
            mode: endpoint
    config-maps:
      watch: false

```

But nonetheless I'm seeing the following errors in the logs, 
```
"Fetching Endpoints KubernetesServiceConfiguration{serviceId='foo-service', name='foo-service', namespace='default', mode='endpoint', port='null', manual=false}
"The resource [foo-service] has multiple ports declared [grpc,http] if you want to to use it in micronaut you have to configure it manually.
```

Am I doing something wrong here or is there some issue in micronaut itself?
Any help is appreciated, thank you for your awesome work with micronaut. 

### Environment Information

- **Operating System: Docker(adoptopenjdk/openjdk11:jdk-11.0.11_9-slim)
- **Micronaut Version: 2.5.3
- **JDK Version: 11

**Comment by pgressa** [comment]
Yeah, seems like the manual configuration wasn't loaded at all otherwise the manual flag would be true. Please try to not use the list like:
```
kubernetes:
  client:
    discovery:
      includes:
        - foo-service
      services:
        foo-service:
            port: grpc
            mode: endpoint
```
