### ISSUE TITLE
How to deal with mounted volumes with the same filename.

### ISSUE THREAD

**Issue by StephanePaulus** [micronaut-projects/micronaut-kubernetes#315]
As far as I know the current Micronaut-Kubernetes integration cannot deal with reading/parsing configmaps/secrets from mounted-volumes that have the same name. 

Example: 
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```
```
......
          volumeMounts:
            - name: secret1
              mountPath: "/etc/micronaut-sandbox/secret1"
              readOnly: true
            - name: secret2
              mountPath: "/etc/micronaut-sandbox/secret2"
              readOnly: true
      volumes:
        - name: secret1
          secret:
            secretName: mysecret
        - name: secret2
          secret:
            secretName: mysecret2
.....
```

I don't think there is a way to deal with this issue. 

`@Value("${username}")` will just return the data of the last one parsed. The same goes for configmaps. A proposed fix could be to include the folder of the mountPath like `@Value("${secret1.username}")` 

Another issue I have discover is that if the configmap or secret "key" starts with a numerical value it will also be ignored. 

Example
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  8d26bd90-7f74-4a08-9fc4-5a5feb61331e : YWRtaW4=
  c07efbea-e85b-4026-90f9-55e40175b16f: MWYyZDFlMmU2N2Rm
```

`@Value("${c07efbea-e85b-4026-90f9-55e40175b16f}")` will work but `@Value("${8d26bd90-7f74-4a08-9fc4-5a5feb61331e }")` will not.
