### ISSUE TITLE
Micronaut - Kubernetes plugin not working for https API endpoints

### ISSUE THREAD

**Issue by sukruthakittur** [micronaut-projects/micronaut-kubernetes#42]
While trying to access kubernetes volume mounted secrets through micronaut application with the below config, I get an error. Do I have the right config? 

```
kubernetes:
  client:
    host: https://my-az-aks-cluster-url
    port: 443
    secure: false
    namespace: default
    secrets:
      enabled: true
      paths:
        - /Users/a871671/Documents/foo
```

`Error while trying to list all Kubernetes Services in the namespace [default] io.micronaut.http.client.exceptions.HttpClientException: Connect error:https`
