### ISSUE TITLE
Allow disabling kubernetes health indicator

### ISSUE THREAD

**Issue by felhag** [micronaut-projects/micronaut-kubernetes#755]
### Feature description

It would be nice and consistent if we would be able to disable the `KubernetesHealthIndicator`, just like can we can do with `DiskSpaceIndicator` and `JdbcIndicator` for example. Something like this: 

```
endpoints:
  health:
    kubernetes:
      enabled: false
```
